# Generated by Django 4.2.30 on 2026-06-15 09:59

from django.db import migrations, models
from django.db.models import Sum


def initialize_total_income(apps, schema_editor):
    UserProfile = apps.get_model('tracker', 'UserProfile')
    Transaction = apps.get_model('tracker', 'Transaction')

    for profile in UserProfile.objects.all().iterator():
        total = (
            Transaction.objects.filter(user_id=profile.user_id, type='income')
            .aggregate(total=Sum('amount'))['total']
            or 0
        )
        profile.total_income = total
        profile.save(update_fields=['total_income'])


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(initialize_total_income, migrations.RunPython.noop),
    ]
