# Generated by Django 4.2.30 on 2026-06-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def create_income_records(apps, schema_editor):
    UserProfile = apps.get_model('tracker', 'UserProfile')
    Income = apps.get_model('tracker', 'Income')

    today = timezone.localdate()
    for profile in UserProfile.objects.exclude(total_income=0).iterator():
        Income.objects.create(
            user_id=profile.user_id,
            amount=profile.total_income,
            date=today,
            description='Total Income',
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_userprofile_total_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.CharField(default='Total Income', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-updated_at'],
            },
        ),
        migrations.RunPython(create_income_records, migrations.RunPython.noop),
    ]
